name: Deploy pages (multi-lecture, simple)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  REPO: ${{ github.event.repository.name }}  # e.g., ps_211

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.2.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile
        
      - name: Install Playwright (Chromium + deps)
        run: npx playwright install --with-deps chromium

      - name: Discover & build all lecture*.md
        shell: bash
        run: |
        set -e
        shopt -s nullglob
        lectures=(lecture*.md)
        if [ ${#lectures[@]} -eq 0 ]; then
            echo "No lecture*.md files found."
            exit 1
        fi

        echo "Found lectures: ${lectures[*]}"

        for f in "${lectures[@]}"; do
            slug="${f%.md}"
            echo "📦 Building $f → dist/$slug  (base=/${REPO}/${slug}/)"
            # 1) Build the SPA and ASK Slidev to include a PDF
            pnpm exec slidev build "$f" \
            --base "/${REPO}/${slug}/" \
            --out "dist/${slug}" \
            --download

            # 2) Fallback: if no PDF showed up, export explicitly
            if ! ls "dist/${slug}"/*.pdf >/dev/null 2>&1; then
            # Try to read exportFilename from the deck (front-matter)
            export_name=$(awk '
                BEGIN{inY=0}
                /^---[[:space:]]*$/{inY=!inY; next}
                inY && $1=="exportFilename:"{print $2; exit}
            ' "$f")

            # Default to slug if not set
            [ -n "$export_name" ] || export_name="$slug"

            echo "🖨  No PDF found after build, exporting → dist/${slug}/${export_name}.pdf"
            pnpm exec slidev export "$f" \
                --format pdf \
                --output "dist/${slug}/${export_name}.pdf"
            fi
        done

        # Generate index that links decks + PDFs (shows real filenames)
        mkdir -p dist
        {
            echo '<!doctype html><meta charset="utf-8"><title>PS 211 — Slide Decks</title>'
            echo '<style>body{font:16px/1.5 system-ui,sans-serif;max-width:800px;margin:2rem auto;padding:0 1rem}ul{line-height:1.8}</style>'
            echo '<h1>PS 211 — Slide Decks</h1><ul>'
            for d in dist/*/ ; do
            [ -f "${d}index.html" ] || continue
            dname=$(basename "$d")
            pdf=$(find "$d" -maxdepth 1 -name '*.pdf' | head -n 1)
            if [ -n "$pdf" ]; then
                echo "<li><a href=\"$dname/\">$dname</a> — <a href=\"$dname/$(basename "$pdf")\">$(basename "$pdf")</a></li>"
            else
                echo "<li><a href=\"$dname/\">$dname</a></li>"
            fi
            done
            echo '</ul>'
        } > dist/index.html
    
      - name: Sanity check output
        run: |
          echo "Top-level dist contents:"
          ls -la dist
          echo "Index files found:"
          find dist -maxdepth 2 -type f -name index.html -print
    
      - name: List built decks & PDFs
        run: |
           echo "Top-level dist:" && ls -la dist
           echo "Deck indexes:" && find dist -maxdepth 2 -type f -name index.html -print
           echo "PDFs:" && find dist -maxdepth 2 -type f -name '*.pdf' -print

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
